import { COLORS } from '../theme/colors';
import type { Subject } from '../types';

export const SUBJECTS: Subject[] = [
  {
    id: 'mathematics',
    name: 'Mathematics',
    iconName: 'calculator',
    color: COLORS.subjects.mathematics,
    gradientColors: ['#4ECDC4', '#2EAF9F'],
    totalTopics: 18,
    completedTopics: 5,
    progressPercent: 28,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'english',
    name: 'English',
    iconName: 'book',
    color: COLORS.subjects.english,
    gradientColors: ['#4A90D9', '#2E6FB0'],
    totalTopics: 14,
    completedTopics: 3,
    progressPercent: 21,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'kiswahili',
    name: 'Kiswahili',
    iconName: 'chatbubbles',
    color: COLORS.subjects.kiswahili,
    gradientColors: ['#FF8C42', '#E06B28'],
    totalTopics: 12,
    completedTopics: 2,
    progressPercent: 17,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'biology',
    name: 'Biology',
    iconName: 'leaf',
    color: COLORS.subjects.biology,
    gradientColors: ['#52C41A', '#389E0D'],
    totalTopics: 16,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    iconName: 'flask',
    color: COLORS.subjects.chemistry,
    gradientColors: ['#7B6FF2', '#5A50CC'],
    totalTopics: 15,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: true,
    form: [1, 2, 3, 4],
  },
  {
    id: 'physics',
    name: 'Physics',
    iconName: 'planet',
    color: COLORS.subjects.physics,
    gradientColors: ['#5C6BC0', '#3949AB'],
    totalTopics: 14,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: true,
    form: [1, 2, 3, 4],
  },
  {
    id: 'geography',
    name: 'Geography',
    iconName: 'globe',
    color: COLORS.subjects.geography,
    gradientColors: ['#10B981', '#059669'],
    totalTopics: 12,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'history',
    name: 'History',
    iconName: 'time',
    color: COLORS.subjects.history,
    gradientColors: ['#F59E0B', '#D97706'],
    totalTopics: 13,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'civics',
    name: 'Civics',
    iconName: 'people',
    color: COLORS.subjects.civics,
    gradientColors: ['#06B6D4', '#0891B2'],
    totalTopics: 10,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'commerce',
    name: 'Commerce',
    iconName: 'trending-up',
    color: COLORS.subjects.commerce,
    gradientColors: ['#EC4899', '#DB2777'],
    totalTopics: 11,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: true,
    form: [3, 4],
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    iconName: 'flower',
    color: COLORS.subjects.agriculture,
    gradientColors: ['#84CC16', '#65A30D'],
    totalTopics: 10,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
  {
    id: 'computerStudies',
    name: 'Computer Studies',
    iconName: 'laptop',
    color: COLORS.subjects.computerStudies,
    gradientColors: ['#8B5CF6', '#7C3AED'],
    totalTopics: 12,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: true,
    form: [1, 2, 3, 4],
  },
  {
    id: 'islamicKnowledge',
    name: 'Islamic Knowledge',
    iconName: 'star',
    color: COLORS.subjects.islamicKnowledge,
    gradientColors: ['#F7C52E', '#D4A017'],
    totalTopics: 10,
    completedTopics: 0,
    progressPercent: 0,
    isPremium: false,
    form: [1, 2, 3, 4],
  },
];

export const SUBJECT_COUNT = SUBJECTS.length;
export const FORM_COUNT = 4;
export const FREE_SUBJECTS = SUBJECTS.filter((s) => !s.isPremium).length;
