import type { SubscriptionPlan } from '../types/subscription';

export const SEED_PLANS: SubscriptionPlan[] = [
  {
    id: 'standard',
    title: 'Standard',
    priceMonthly: 4999,
    priceYearly: 40000,
    maxDevices: 2,
    maxProfiles: 1,
    description: 'Full premium access for one student, on up to 2 devices.',
    features: ['summary', 'hoq', 'exam_mode', 'advanced_analytics', 'past_papers', 'ai_tutor'],
  },
  {
    id: 'family',
    title: 'Family Pack',
    priceMonthly: 7999,
    priceYearly: 60000,
    maxDevices: 5,
    maxProfiles: 4,
    description: '1 primary account + 3 student profiles, on up to 5 devices — best value!',
    isPopular: true,
    features: ['summary', 'hoq', 'exam_mode', 'advanced_analytics', 'past_papers', 'ai_tutor'],
  },
];

export const FEATURE_META: Record<
  string,
  { title: string; description: string; iconName: string }
> = {
  summary: {
    title: 'AI Summaries',
    description: 'Concise topic summaries generated by AI — study smarter.',
    iconName: 'document-text-outline',
  },
  hoq: {
    title: 'Higher Order Questions',
    description: "NECTA's most tested format — critical thinking & analysis.",
    iconName: 'bulb-outline',
  },
  exam_mode: {
    title: 'Exam Mode',
    description: 'Timed mock exams that simulate the real NECTA experience.',
    iconName: 'timer-outline',
  },
  advanced_analytics: {
    title: 'Advanced Analytics',
    description: 'Deep performance insights — identify gaps and track growth.',
    iconName: 'bar-chart-outline',
  },
  past_papers: {
    title: 'Past Papers',
    description: 'Full NECTA past paper archive with worked solutions.',
    iconName: 'library-outline',
  },
  ai_tutor: {
    title: 'AI Tutor',
    description: 'Ask questions, get step-by-step explanations, 24/7.',
    iconName: 'chatbubbles-outline',
  },
};

export const PAYMENT_META: Record<
  string,
  { label: string; logo: string; instructions: string; requiresPhone: boolean }
> = {
  google_play: {
    label: 'Google Play',
    logo: 'logo-google-playstore',
    instructions: 'Billed via Google Play Store. One tap, secure payment.',
    requiresPhone: false,
  },
  airtel: {
    label: 'Airtel Money',
    logo: 'phone-portrait-outline',
    instructions: 'Enter your Airtel number. You will receive a USSD push prompt.',
    requiresPhone: true,
  },
  mpesa: {
    label: 'M-Pesa (Vodacom)',
    logo: 'phone-portrait-outline',
    instructions: 'Enter your Vodacom M-Pesa number. Confirm the push notification.',
    requiresPhone: true,
  },
  tigo: {
    label: 'Tigo Pesa',
    logo: 'phone-portrait-outline',
    instructions: 'Enter your Tigo number. You will receive a USSD payment prompt.',
    requiresPhone: true,
  },
  halopesa: {
    label: 'Halopesa (Halotel)',
    logo: 'phone-portrait-outline',
    instructions: 'Enter your Halotel number. Approve the payment push.',
    requiresPhone: true,
  },
  ttcl: {
    label: 'TTCL Pesa',
    logo: 'phone-portrait-outline',
    instructions: 'Enter your TTCL number. Confirm the M-Pesa-style push.',
    requiresPhone: true,
  },
  whatsapp: {
    label: 'WhatsApp Support',
    logo: 'logo-whatsapp',
    instructions: 'Chat with our support team on WhatsApp to complete your payment.',
    requiresPhone: false,
  },
};
