import type { BadgeDefinition } from '../types/gamification';
import { COLORS } from '../theme';

export const SEED_BADGES: BadgeDefinition[] = [
  {
    id: 'first_quiz',
    title: 'First Quiz Completed',
    description: 'Complete your very first quiz.',
    iconName: 'school',
    requirement: 'Complete 1 quiz',
    rarity: 'common',
    color: COLORS.primary,
  },
  {
    id: 'first_perfect',
    title: 'First Perfect Score',
    description: 'Get 100% on any quiz.',
    iconName: 'ribbon',
    requirement: 'Score 100% on a quiz',
    rarity: 'rare',
    color: COLORS.gold,
  },
  {
    id: 'streak_3',
    title: '3-Day Streak',
    description: 'Study 3 days in a row.',
    iconName: 'flame',
    requirement: '3-day streak',
    rarity: 'common',
    color: '#FF8C42',
  },
  {
    id: 'streak_7',
    title: '7-Day Streak',
    description: 'Study 7 days in a row — weekly warrior!',
    iconName: 'trophy',
    requirement: '7-day streak',
    rarity: 'rare',
    color: COLORS.gold,
  },
  {
    id: 'math_starter',
    title: 'Math Starter',
    description: 'Complete a Mathematics quiz.',
    iconName: 'calculator',
    requirement: 'Complete any Math quiz',
    rarity: 'common',
    color: COLORS.subjects.mathematics,
  },
  {
    id: 'science_explorer',
    title: 'Science Explorer',
    description: 'Complete quizzes in 2 science subjects.',
    iconName: 'flask',
    requirement: 'Complete quizzes in Biology & Chemistry',
    rarity: 'rare',
    color: COLORS.subjects.biology,
  },
  {
    id: 'fast_learner',
    title: 'Fast Learner',
    description: 'Answer 3 MCQ questions in under 15s each.',
    iconName: 'flash',
    requirement: 'Answer 3 MCQs under 15s each',
    rarity: 'rare',
    color: COLORS.success,
  },
  {
    id: 'comeback',
    title: 'Comeback Student',
    description: 'Return after missing 7+ days.',
    iconName: 'refresh-circle',
    requirement: 'Return after a 7-day absence',
    rarity: 'common',
    color: COLORS.info,
  },
  {
    id: 'form1_champion',
    title: 'Form 1 Champion',
    description: 'Complete all Form 1 topics.',
    iconName: 'medal',
    requirement: 'Complete all Form 1 topics',
    rarity: 'epic',
    color: COLORS.goldLight,
  },
  {
    id: 'premium_learner',
    title: 'Premium Learner',
    description: 'Activate a Premium subscription.',
    iconName: 'star',
    requirement: 'Upgrade to Premium',
    rarity: 'rare',
    color: COLORS.gold,
  },
];

export const DAILY_MISSIONS = [
  {
    id: 'mission_questions',
    type: 'questions_answered' as const,
    title: 'Answer 5 Questions',
    description: 'Answer any 5 quiz questions today.',
    targetCount: 5,
    xpReward: 50,
    coinsReward: 5,
    iconName: 'help-circle-outline',
  },
  {
    id: 'mission_quiz',
    type: 'quizzes_completed' as const,
    title: 'Complete 1 Quiz',
    description: 'Finish any quiz from start to end.',
    targetCount: 1,
    xpReward: 50,
    coinsReward: 10,
    iconName: 'checkmark-circle-outline',
  },
  {
    id: 'mission_xp',
    type: 'xp_earned_today' as const,
    title: 'Earn 50 XP Today',
    description: 'Accumulate 50 XP in a single day.',
    targetCount: 50,
    xpReward: 0,
    coinsReward: 25,
    iconName: 'flash-outline',
  },
];
