/**
 * Seed questions for Phase 3 quiz engine.
 * Real Tanzania O-Level difficulty questions for Mathematics, Biology, Geography (Form 1).
 *
 * Pack ID format (from seedData.ts generator):
 *   {formId}_{subjectKey}_topic_{N}_pack_{M}
 *   Pack order: 1=MCQ, 2=TF, 3=FIB, 4=Summary(premium), 5=HOQ(premium)
 */

import type { Question } from '../types/quiz';

const NOW = Date.now();

// ─── Mathematics — Form 2 Topic 1 (Linear Equations and Inequalities) ─────────

const MATH_PACK_PREFIX = 'form_1_mathematics_topic_1';

const MATH_MCQ: Question[] = [
  {
    id: 'math_mcq_1',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Solve for x:\n\\( 2x + 3 = 11 \\)',
    options: [
      { id: 'a', text: 'x = 3', isCorrect: false },
      { id: 'b', text: 'x = 4', isCorrect: true },
      { id: 'c', text: 'x = 5', isCorrect: false },
      { id: 'd', text: 'x = 7', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Subtract 3 from both sides: 2x = 8. Then divide by 2: x = 4.',
    difficulty: 'easy',
    xpReward: 10,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_mcq_2',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'What is the gradient of a line passing through (0, 1) and (2, 5)?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '3', isCorrect: false },
      { id: 'd', text: '4', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Gradient m = (5 − 1) ÷ (2 − 0) = 4 ÷ 2 = 2.',
    difficulty: 'medium',
    xpReward: 12,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_mcq_3',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Solve the inequality:\n\\( 3x - 6 > 9 \\)',
    options: [
      { id: 'a', text: 'x > 1', isCorrect: false },
      { id: 'b', text: 'x > 3', isCorrect: false },
      { id: 'c', text: 'x > 5', isCorrect: true },
      { id: 'd', text: 'x < 5', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Add 6 to both sides: 3x > 15. Divide by 3: x > 5.',
    difficulty: 'medium',
    xpReward: 12,
    order: 3,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_mcq_4',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'A shopkeeper buys goods for Tsh 8,000 and sells for Tsh 10,000. What is the profit percentage?',
    options: [
      { id: 'a', text: '20%', isCorrect: false },
      { id: 'b', text: '25%', isCorrect: true },
      { id: 'c', text: '30%', isCorrect: false },
      { id: 'd', text: '40%', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Profit = 10,000 − 8,000 = 2,000. Profit% = (2,000 ÷ 8,000) × 100 = 25%.',
    difficulty: 'medium',
    xpReward: 12,
    order: 4,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_mcq_5',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Solve simultaneously: x + y = 5 and x − y = 1. What is x?',
    options: [
      { id: 'a', text: 'x = 1', isCorrect: false },
      { id: 'b', text: 'x = 2', isCorrect: false },
      { id: 'c', text: 'x = 3', isCorrect: true },
      { id: 'd', text: 'x = 4', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Add both equations: 2x = 6, so x = 3. Then y = 5 − 3 = 2.',
    difficulty: 'medium',
    xpReward: 12,
    order: 5,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const MATH_FIB: Question[] = [
  {
    id: 'math_fib_1',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'The sum of angles in a triangle is ___ degrees.',
    options: [],
    correctAnswer: '180',
    explanation: 'The angle sum theorem states that interior angles of any triangle add up to 180°.',
    difficulty: 'easy',
    xpReward: 8,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_fib_2',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'If 5x = 35, then x = ___',
    options: [],
    correctAnswer: '7',
    explanation: 'Divide both sides by 5: x = 35 ÷ 5 = 7.',
    difficulty: 'easy',
    xpReward: 8,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_fib_3',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'The value of x in the equation x − 8 = 12 is ___',
    options: [],
    correctAnswer: '20',
    explanation: 'Add 8 to both sides: x = 12 + 8 = 20.',
    difficulty: 'easy',
    xpReward: 8,
    order: 3,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const MATH_TF: Question[] = [
  {
    id: 'math_tf_1',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_2`,
    type: 'tf',
    questionText: 'The solution to the equation 2x + 4 = 16 is x = 7.',
    options: [],
    correctAnswer: 'false',
    explanation: '2x = 16 − 4 = 12, so x = 6, not 7.',
    difficulty: 'easy',
    xpReward: 7,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'math_tf_2',
    formId: 'form_1',
    subjectId: 'form_1_mathematics',
    topicId: `${MATH_PACK_PREFIX}`,
    learningPackId: `${MATH_PACK_PREFIX}_pack_2`,
    type: 'tf',
    questionText: 'Two simultaneous linear equations always have exactly one solution.',
    options: [],
    correctAnswer: 'false',
    explanation: 'They can have no solution (parallel lines) or infinitely many solutions (the same line).',
    difficulty: 'medium',
    xpReward: 9,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ─── Biology — Form 2 Topic 1 (Nutrition in Plants and Animals) ───────────────

const BIO_PACK_PREFIX = 'form_1_biology_topic_1';

const BIO_MCQ: Question[] = [
  {
    id: 'bio_mcq_1',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Which organelle is known as the "powerhouse of the cell"?',
    options: [
      { id: 'a', text: 'Nucleus', isCorrect: false },
      { id: 'b', text: 'Mitochondria', isCorrect: true },
      { id: 'c', text: 'Ribosome', isCorrect: false },
      { id: 'd', text: 'Chloroplast', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Mitochondria produce ATP through cellular respiration, supplying energy for all cell activities.',
    difficulty: 'easy',
    xpReward: 10,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_mcq_2',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'The process by which plants manufacture food using sunlight is called:',
    options: [
      { id: 'a', text: 'Respiration', isCorrect: false },
      { id: 'b', text: 'Transpiration', isCorrect: false },
      { id: 'c', text: 'Photosynthesis', isCorrect: true },
      { id: 'd', text: 'Digestion', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Photosynthesis uses light energy, water and CO₂ to produce glucose and oxygen.',
    difficulty: 'easy',
    xpReward: 10,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_mcq_3',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'The photosynthesis equation uses which gas as a raw material?',
    options: [
      { id: 'a', text: 'Oxygen', isCorrect: false },
      { id: 'b', text: 'Nitrogen', isCorrect: false },
      { id: 'c', text: 'Carbon dioxide', isCorrect: true },
      { id: 'd', text: 'Hydrogen', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: '6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. CO₂ is absorbed, O₂ is released.',
    difficulty: 'easy',
    xpReward: 10,
    order: 3,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_mcq_4',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'How many chambers does the human heart have?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: false },
      { id: 'c', text: '4', isCorrect: true },
      { id: 'd', text: '5', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Four chambers: right atrium, right ventricle, left atrium, and left ventricle.',
    difficulty: 'easy',
    xpReward: 10,
    order: 4,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_mcq_5',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Which enzyme in saliva begins the digestion of starch?',
    options: [
      { id: 'a', text: 'Pepsin', isCorrect: false },
      { id: 'b', text: 'Lipase', isCorrect: false },
      { id: 'c', text: 'Amylase', isCorrect: true },
      { id: 'd', text: 'Trypsin', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Salivary amylase (ptyalin) breaks down starch into maltose in the mouth.',
    difficulty: 'medium',
    xpReward: 12,
    order: 5,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const BIO_FIB: Question[] = [
  {
    id: 'bio_fib_1',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'The green pigment in plant leaves used to absorb light energy is called ___',
    options: [],
    correctAnswer: 'chlorophyll',
    explanation: 'Chlorophyll is found in chloroplasts and absorbs red and blue light for photosynthesis.',
    difficulty: 'easy',
    xpReward: 8,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_fib_2',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'Blood travels from the heart to the lungs through the ___ artery.',
    options: [],
    correctAnswer: 'pulmonary',
    explanation: 'The pulmonary artery carries deoxygenated blood from the right ventricle to the lungs.',
    difficulty: 'medium',
    xpReward: 10,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_fib_3',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'The basic unit of all living organisms is the ___',
    options: [],
    correctAnswer: 'cell',
    explanation: 'Cell theory: all living things are made of cells, the smallest unit of life.',
    difficulty: 'easy',
    xpReward: 8,
    order: 3,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const BIO_TF: Question[] = [
  {
    id: 'bio_tf_1',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_2`,
    type: 'tf',
    questionText: 'Plants release carbon dioxide as a product of photosynthesis.',
    options: [],
    correctAnswer: 'false',
    explanation: 'Plants absorb CO₂ and release O₂ during photosynthesis. CO₂ is only released during respiration.',
    difficulty: 'easy',
    xpReward: 7,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bio_tf_2',
    formId: 'form_1',
    subjectId: 'form_1_biology',
    topicId: `${BIO_PACK_PREFIX}`,
    learningPackId: `${BIO_PACK_PREFIX}_pack_2`,
    type: 'tf',
    questionText: 'The small intestine is the main site for digestion and absorption of nutrients.',
    options: [],
    correctAnswer: 'true',
    explanation: 'The small intestine, aided by pancreatic and liver enzymes, absorbs most nutrients into the blood.',
    difficulty: 'easy',
    xpReward: 7,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ─── Geography — Form 2 Topic 1 (Rocks and Weathering) ────────────────────────

const GEO_PACK_PREFIX = 'form_1_geography_topic_1';

const GEO_MCQ: Question[] = [
  {
    id: 'geo_mcq_1',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'What is the highest mountain in Africa?',
    options: [
      { id: 'a', text: 'Mount Kenya', isCorrect: false },
      { id: 'b', text: 'Mount Kilimanjaro', isCorrect: true },
      { id: 'c', text: 'Mount Elgon', isCorrect: false },
      { id: 'd', text: 'Ruwenzori', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Mount Kilimanjaro in Tanzania rises to 5,895 m — Africa\'s tallest peak.',
    difficulty: 'easy',
    xpReward: 10,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_mcq_2',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Which of the following is an igneous rock?',
    options: [
      { id: 'a', text: 'Limestone', isCorrect: false },
      { id: 'b', text: 'Marble', isCorrect: false },
      { id: 'c', text: 'Granite', isCorrect: true },
      { id: 'd', text: 'Shale', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Granite forms from cooled magma (igneous = fire-formed). Marble is metamorphic; limestone and shale are sedimentary.',
    difficulty: 'medium',
    xpReward: 12,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_mcq_3',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'What is the in-situ breakdown of rocks through physical, chemical and biological processes?',
    options: [
      { id: 'a', text: 'Erosion', isCorrect: false },
      { id: 'b', text: 'Weathering', isCorrect: true },
      { id: 'c', text: 'Deposition', isCorrect: false },
      { id: 'd', text: 'Transportation', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Weathering is the breakdown of rocks in place. Erosion involves the movement of broken material.',
    difficulty: 'easy',
    xpReward: 10,
    order: 3,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_mcq_4',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Lake Victoria is shared by which three countries?',
    options: [
      { id: 'a', text: 'Tanzania and Kenya only', isCorrect: false },
      { id: 'b', text: 'Tanzania, Kenya and Uganda', isCorrect: true },
      { id: 'c', text: 'Tanzania and Uganda only', isCorrect: false },
      { id: 'd', text: 'Kenya, Uganda and Rwanda', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Lake Victoria borders Tanzania, Kenya and Uganda. It is the world\'s second largest freshwater lake.',
    difficulty: 'medium',
    xpReward: 12,
    order: 4,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_mcq_5',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_1`,
    type: 'mcq',
    questionText: 'Which type of rock forms from compacted layers of sediment?',
    options: [
      { id: 'a', text: 'Igneous', isCorrect: false },
      { id: 'b', text: 'Metamorphic', isCorrect: false },
      { id: 'c', text: 'Sedimentary', isCorrect: true },
      { id: 'd', text: 'Volcanic', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'Sedimentary rocks (e.g., sandstone, limestone) form from compressed sediment layers over time.',
    difficulty: 'easy',
    xpReward: 10,
    order: 5,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const GEO_FIB: Question[] = [
  {
    id: 'geo_fib_1',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'The official capital city of Tanzania is ___',
    options: [],
    correctAnswer: 'Dodoma',
    explanation: 'Dodoma became Tanzania\'s official legislative capital in 1996, replacing Dar es Salaam.',
    difficulty: 'easy',
    xpReward: 8,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_fib_2',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'The type of weathering that involves chemical changes in rock minerals is called ___ weathering.',
    options: [],
    correctAnswer: 'chemical',
    explanation: 'Chemical weathering includes oxidation, hydration and carbonation — processes that change the rock\'s mineral composition.',
    difficulty: 'medium',
    xpReward: 10,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_fib_3',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_3`,
    type: 'fib',
    questionText: 'Tanzania is located in ___ Africa.',
    options: [],
    correctAnswer: 'East',
    explanation: 'Tanzania is part of the East African region, sharing borders with Kenya, Uganda, Rwanda, Burundi, DRC, Zambia, Malawi, Mozambique and the Indian Ocean.',
    difficulty: 'easy',
    xpReward: 8,
    order: 3,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const GEO_TF: Question[] = [
  {
    id: 'geo_tf_1',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_2`,
    type: 'tf',
    questionText: 'Mount Kilimanjaro is an active volcano located in Kenya.',
    options: [],
    correctAnswer: 'false',
    explanation: 'Kilimanjaro is a dormant (not active) stratovolcano and is located in Tanzania, not Kenya.',
    difficulty: 'easy',
    xpReward: 7,
    order: 1,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'geo_tf_2',
    formId: 'form_1',
    subjectId: 'form_1_geography',
    topicId: `${GEO_PACK_PREFIX}`,
    learningPackId: `${GEO_PACK_PREFIX}_pack_2`,
    type: 'tf',
    questionText: 'Soil is formed partly through the weathering of rocks.',
    options: [],
    correctAnswer: 'true',
    explanation: 'Weathering breaks rocks into mineral particles that, combined with organic matter, form soil over time.',
    difficulty: 'easy',
    xpReward: 7,
    order: 2,
    isActive: true,
    isPremium: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ─── Combined export ───────────────────────────────────────────────────────────

const ALL_SEED_QUESTIONS: Question[] = [
  ...MATH_MCQ,
  ...MATH_FIB,
  ...MATH_TF,
  ...BIO_MCQ,
  ...BIO_FIB,
  ...BIO_TF,
  ...GEO_MCQ,
  ...GEO_FIB,
  ...GEO_TF,
];

let _questions: Question[] | null = null;

export function getSeedQuestions(): Question[] {
  if (!_questions) _questions = ALL_SEED_QUESTIONS;
  return _questions;
}

export function getSeedQuestionsByPack(learningPackId: string): Question[] {
  return getSeedQuestions()
    .filter((q) => q.learningPackId === learningPackId && q.isActive)
    .sort((a, b) => a.order - b.order);
}
